[tool.poetry]
name = "b3p"
version = "0.1.0"
description = "Command line tools for preprocessing of wind turbine blades"
authors = ["wr1 <8971152+wr1@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyarrow = "^15.0.2"
pandas = "^2.2.2"
numpy = "^1.26.4"
scipy = "^1.13.0"
ruamel-yaml = "^0.18.6"
fire = "^0.6.0"
vtk = "^9.3.0"
pyvista = "^0.43.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"



[tool.poetry.scripts]
        b3p = "b3p.b3p_cli:main"
        b3p_slab_plot = "utils.slab_plot:main"
        b3p_drape_plot = "utils.drape_plot:main"
        b3p_aero = "b3p.ccblade_run:main"


